name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      draft:
        description: 'Publish release as draft'
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: apk-mitm-tool-linux-amd64.tar.gz
            bin_name: apk-mitm-tool
          - os: windows-latest
            asset_name: apk-mitm-tool-windows-amd64.zip
            bin_name: apk-mitm-tool.exe
          - os: macos-latest
            asset_name: apk-mitm-tool-macos-amd64.tar.gz
            bin_name: apk-mitm-tool
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconsole --onefile --hidden-import tkinterdnd2 --collect-all tkinterdnd2 main.py --name apk-mitm-tool

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd dist
          Compress-Archive -Path ${{ matrix.bin_name }} -DestinationPath ../${{ matrix.asset_name }}
        shell: powershell

      - name: Package (macOS & Linux)
        if: runner.os != 'Windows'
        run: |
          cd dist
          tar -czf ../${{ matrix.asset_name }} ${{ matrix.bin_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*
          draft: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.draft == 'true' }}
          generate_release_notes: true
